# this is the db container
db:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASS=postgres

# This is the bundle install container, all gems will be installed here
box:
  image: busybox
  volumes:
    - /box

# This is the rails container, where your app will be delivered
web: &default
  build: .
  command: ./script/start.sh
  volumes:
    - .:/usr/src/app
  volumes_from:
    - box
  hostname: padawan
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    - DB_USER=postgres
    - DB_PASSWORD=postgres
    - DB_HOST=db
